apiVersion: v1
kind: ConfigMap

metadata:
  name: backend-config
  namespace: wardro

data:
  SPRING_PROFILES_ACTIVE: prod
  SERVER_PORT: "8080"

  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-service:5432/wardrodb

  JWT_EXPIRATION: "86400000"